### ISSUE TITLE
[Bug]: scrolling trough sights list restarts application

### ISSUE THREAD

**Issue by Ewoodss** [TI-2-2-A1-2122/picum#43]
### Contact Details

we.baars@student.avans.nl

### What happened?

A bug happened!

i scrolled throug the sights list, then the app restarted.

### Relevant log output

```shell
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: nl.ags.picum, PID: 26165
    android.content.res.Resources$NotFoundException: Resource ID #0x0
        at android.content.res.ResourcesImpl.getValueForDensity(ResourcesImpl.java:246)
        at android.content.res.Resources.getDrawableForDensity(Resources.java:982)
        at android.content.res.Resources.getDrawable(Resources.java:922)
        at android.content.Context.getDrawable(Context.java:693)
        at nl.ags.picum.UI.Util.SightAdapter.onBindViewHolder(SightAdapter.java:50)
        at nl.ags.picum.UI.Util.SightAdapter.onBindViewHolder(SightAdapter.java:29)
        at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:7065)
        at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7107)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6012)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6279)
        at androidx.recyclerview.widget.GapWorker.prefetchPositionWithDeadline(GapWorker.java:288)
        at androidx.recyclerview.widget.GapWorker.flushTaskWithDeadline(GapWorker.java:345)
        at androidx.recyclerview.widget.GapWorker.flushTasksWithDeadline(GapWorker.java:361)
        at androidx.recyclerview.widget.GapWorker.prefetch(GapWorker.java:368)
        at androidx.recyclerview.widget.GapWorker.run(GapWorker.java:399)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

**Comment by Ewoodss** [comment]
this bug seems to be gone
